name: Copado API Call

on:
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call Copado Builds API
        run: |
          curl -X GET "https://eu-robotic.copado.com/pace/v4/projects/73283/builds" \
          -H "accept: application/json" \
          -H "cookie: $COPADO_COOKIE"
        env:
          COPADO_COOKIE: ${{ secrets.COPADO_COOKIE }}
